name: services_providers
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3  
  flutter_localizations: # Text direction support
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.2.5
  permission_handler: ^12.0.1
  location: ^5.0.3
  geocoding: ^4.0.0
  google_maps_cluster_manager: ^2.0.0
  provider: ^6.1.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  image_picker: ^1.1.2
  file_picker: ^8.3.1
  google_sign_in: ^5.0.7
  intl: ^0.19.0 # Updated to resolve version conflict
  shared_preferences: ^2.5.1
  uuid: ^4.5.1
  firebase_app_check: ^0.3.2+2
  firebase_ml_model_downloader: ^0.3.3
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.4
  googleapis_auth: ^1.6.0
  pin_code_fields: ^8.0.1

  rename: 
  

  # google_ml_kit: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_lints: ^5.0.0
  connectivity_plus: ^6.1.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  image_path: "asset/images/bahj.png"
  min_sdk_android: 23  

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/config/service-account.json
  # fonts:
  #   - family: ElMessiri
  #     fonts:
  #       - asset: fonts/ElMessiri-Regular.ttf
  #       - asset: fonts/ElMessiri-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/ElMessiri-Bold.ttf
  #         weight: 700
  #   - family: Amiri
  #     fonts:
  #       - asset: fonts/Amiri-Regular.ttf
  #       - asset: fonts/Amiri-Bold.ttf
  #         weight: 700